// <auto-generated />
using System;
using HeThongDatLich.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongDatLich.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527141343_HeThongV2")]
    partial class HeThongV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongDatLich.Models.DANHGIA", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("MaDatLich")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDatLich");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("HeThongDatLich.Models.DONDATLICH", b =>
                {
                    b.Property<int>("MaDatLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatLich"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KhungGio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaHDV")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaTour")
                        .HasColumnType("int");

                    b.Property<int?>("MaVoucher")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("date");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDatLich");

                    b.HasIndex("MaHDV");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaTour");

                    b.HasIndex("MaVoucher");

                    b.ToTable("DonDatLichs");
                });

            modelBuilder.Entity("HeThongDatLich.Models.GOITOUR", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTour"));

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("MaHDV")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThoiGian")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTour");

                    b.HasIndex("MaHDV");

                    b.ToTable("GoiTours");
                });

            modelBuilder.Entity("HeThongDatLich.Models.HOADON", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaDatLich")
                        .HasColumnType("int");

                    b.Property<int>("MaPTTT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal?>("SoTienGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<bool>("TrangThaiTT")
                        .HasColumnType("bit");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDatLich")
                        .IsUnique();

                    b.HasIndex("MaPTTT");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("HeThongDatLich.Models.HOSOHDV", b =>
                {
                    b.Property<int>("MaHDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("GioiThieu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("KinhNghiem")
                        .HasColumnType("int");

                    b.Property<int>("MaNgonNgu")
                        .HasColumnType("int");

                    b.Property<int>("MaPhuongXa")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThaiHoatDong")
                        .HasColumnType("int");

                    b.HasKey("MaHDV");

                    b.HasIndex("MaNgonNgu");

                    b.HasIndex("MaPhuongXa");

                    b.ToTable("HoSoHDVs");
                });

            modelBuilder.Entity("HeThongDatLich.Models.MAGIAMGIA", b =>
                {
                    b.Property<int>("MaVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVoucher"));

                    b.Property<decimal>("GiamToiDa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVoucher");

                    b.ToTable("MaGiamGias");
                });

            modelBuilder.Entity("HeThongDatLich.Models.NGONNGU", b =>
                {
                    b.Property<int>("MaNgonNgu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNgonNgu"));

                    b.Property<string>("TenNgonNgu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNgonNgu");

                    b.ToTable("NgonNgus");
                });

            modelBuilder.Entity("HeThongDatLich.Models.NGUOIDUNG", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool?>("TrangThaiKhoa")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("HeThongDatLich.Models.PHANQUYEN", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung", "MaQuyen");

                    b.HasIndex("MaQuyen");

                    b.ToTable("PhanQuyens");
                });

            modelBuilder.Entity("HeThongDatLich.Models.PHUONGTHUCTHANHTOAN", b =>
                {
                    b.Property<int>("MaPTTT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPTTT"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPTTT");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("HeThongDatLich.Models.PHUONGXA", b =>
                {
                    b.Property<int>("MaPhuongXa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongXa"));

                    b.Property<int>("MaTinh")
                        .HasColumnType("int");

                    b.Property<string>("TenPhuongXa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhuongXa");

                    b.HasIndex("MaTinh");

                    b.ToTable("PhuongXas");
                });

            modelBuilder.Entity("HeThongDatLich.Models.QUYEN", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen");

                    b.ToTable("Quyens");
                });

            modelBuilder.Entity("HeThongDatLich.Models.TINHTHANH", b =>
                {
                    b.Property<int>("MaTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinh"));

                    b.Property<string>("TenTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTinh");

                    b.ToTable("TinhThanhs");
                });

            modelBuilder.Entity("HeThongDatLich.Models.DANHGIA", b =>
                {
                    b.HasOne("HeThongDatLich.Models.DONDATLICH", "DonDatLich")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaDatLich")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatLich");
                });

            modelBuilder.Entity("HeThongDatLich.Models.DONDATLICH", b =>
                {
                    b.HasOne("HeThongDatLich.Models.HOSOHDV", "HDV")
                        .WithMany("DonDatLichs")
                        .HasForeignKey("MaHDV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatLich.Models.NGUOIDUNG", "KhachHang")
                        .WithMany("DonDatLichs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatLich.Models.GOITOUR", "GoiTour")
                        .WithMany("DonDatLichs")
                        .HasForeignKey("MaTour");

                    b.HasOne("HeThongDatLich.Models.MAGIAMGIA", "MaGiamGia")
                        .WithMany("DonDatLichs")
                        .HasForeignKey("MaVoucher");

                    b.Navigation("GoiTour");

                    b.Navigation("HDV");

                    b.Navigation("KhachHang");

                    b.Navigation("MaGiamGia");
                });

            modelBuilder.Entity("HeThongDatLich.Models.GOITOUR", b =>
                {
                    b.HasOne("HeThongDatLich.Models.HOSOHDV", "HDV")
                        .WithMany("GoiTours")
                        .HasForeignKey("MaHDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HDV");
                });

            modelBuilder.Entity("HeThongDatLich.Models.HOADON", b =>
                {
                    b.HasOne("HeThongDatLich.Models.DONDATLICH", "DonDatLich")
                        .WithOne("HoaDon")
                        .HasForeignKey("HeThongDatLich.Models.HOADON", "MaDatLich")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatLich.Models.PHUONGTHUCTHANHTOAN", "PhuongThucThanhToan")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaPTTT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatLich");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("HeThongDatLich.Models.HOSOHDV", b =>
                {
                    b.HasOne("HeThongDatLich.Models.NGUOIDUNG", "NguoiDung")
                        .WithOne("HDV")
                        .HasForeignKey("HeThongDatLich.Models.HOSOHDV", "MaHDV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatLich.Models.NGONNGU", "NgonNgu")
                        .WithMany("HDVs")
                        .HasForeignKey("MaNgonNgu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongDatLich.Models.PHUONGXA", "PhuongXa")
                        .WithMany("HDVs")
                        .HasForeignKey("MaPhuongXa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NgonNgu");

                    b.Navigation("NguoiDung");

                    b.Navigation("PhuongXa");
                });

            modelBuilder.Entity("HeThongDatLich.Models.PHANQUYEN", b =>
                {
                    b.HasOne("HeThongDatLich.Models.NGUOIDUNG", "NguoiDung")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongDatLich.Models.QUYEN", "Quyen")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("HeThongDatLich.Models.PHUONGXA", b =>
                {
                    b.HasOne("HeThongDatLich.Models.TINHTHANH", "TinhThanh")
                        .WithMany("PhuongXas")
                        .HasForeignKey("MaTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("HeThongDatLich.Models.DONDATLICH", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("HoaDon")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongDatLich.Models.GOITOUR", b =>
                {
                    b.Navigation("DonDatLichs");
                });

            modelBuilder.Entity("HeThongDatLich.Models.HOSOHDV", b =>
                {
                    b.Navigation("DonDatLichs");

                    b.Navigation("GoiTours");
                });

            modelBuilder.Entity("HeThongDatLich.Models.MAGIAMGIA", b =>
                {
                    b.Navigation("DonDatLichs");
                });

            modelBuilder.Entity("HeThongDatLich.Models.NGONNGU", b =>
                {
                    b.Navigation("HDVs");
                });

            modelBuilder.Entity("HeThongDatLich.Models.NGUOIDUNG", b =>
                {
                    b.Navigation("DonDatLichs");

                    b.Navigation("HDV");

                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("HeThongDatLich.Models.PHUONGTHUCTHANHTOAN", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("HeThongDatLich.Models.PHUONGXA", b =>
                {
                    b.Navigation("HDVs");
                });

            modelBuilder.Entity("HeThongDatLich.Models.QUYEN", b =>
                {
                    b.Navigation("PhanQuyens");
                });

            modelBuilder.Entity("HeThongDatLich.Models.TINHTHANH", b =>
                {
                    b.Navigation("PhuongXas");
                });
#pragma warning restore 612, 618
        }
    }
}
